### ISSUE TITLE
No detection of changes when library contains hyphens

### ISSUE THREAD

**Issue by ensc** [lu-zero/cargo-c#441]
When trying to keep nice filenames with hyphens,  cargo-c creates both the wanted files and mess from cargo ('-' replaced by '_').

E.g. after

```toml
[package.metadata.capi.library]
name = "test-foo"
```

there will be created (when building from scratch)

```
libtest-foo.a
libtest-foo.so
libtest_foo.a
libtest_foo.so
```

When doing changes, only the underscore variants will be rebuilt.  Then the hash function calculates the hash function over the requested files (which have not been changed) to see if something changed and exits without regenerating headers.

E.g. content of build directory is (note the dates)

```
-rw-r--r--. Feb 10 18:52 libtest-foo.a
-rwxr-xr-x. Feb 10 18:52 libtest-foo.so
-rw-r--r--. Feb 10 18:53 libtest_foo.a
-rw-r--r--. Feb 10 18:52 libtest_foo.d
-rwxr-xr-x. Feb 10 18:53 libtest_foo.so
```

Effect is, that when running `cargo cbuild` on

```rust
#[no_mangle]
pub extern "C" fn add(left: u64, right: u64) -> u64 {
    left + right
}
```

and changing this later to

```rust
#[no_mangle]
pub extern "C" fn sub(left: u64, right: u64) -> u64 {
    left - right
}
```

the generated wrapper header still contains

```c
uint64_t add(uint64_t left, uint64_t right);
```

but not `sub()`.

**Comment by lu-zero** [comment]
It is a duplicate of #208 if you feel like to send a PR I'll be grateful, otherwise I hope to address it one of the future weekends

**Comment by lu-zero** [comment]
Should be fixed now

**Comment by ensc** [comment]
problem still happens with 90c6024534681b84d1ea5fa3833c50c57cb76fe0

Issue seems to be that the library is created both with dashes and underscores:
- on first `cargo cbuild`, `libtest-foo.a` + `libtest_foo.a` are created
- on second `cargo cbuild` (and after changing the interface), only `libtest_foo.a` will be updated but `libtest-foo.a` stays as-is.  Hash is calculated over `libtest-foo.a` and does not change so that `.h` won't be updated.

**Comment by lu-zero** [comment]
if you change the metadata now the resulting hash must change...

**Comment by ensc** [comment]
I do not change the metadata;  I change the source (e.g. add a `fn sub()` in `src/lib.rs`);  the generated header will not be updated and contains the old content.

**Comment by lu-zero** [comment]
Ah, then it is even simpler to fix.

**Comment by lu-zero** [comment]
Please confirm, I'd cut the release next weekend :)

**Comment by ensc** [comment]
header is now rebuilt when changing the library; thx.

But comment above your changes does not reflect the actual code anymore

```rust
        // it is a new build, build the additional files and update update the cache
        // if the hash value does not match.
        if new_build || !cpkg.finger_print.is_valid() {
```
